### ISSUE TITLE
SQL Dump

### ISSUE THREAD

**Issue by jens40** [akramrana/affiliate-marketing#1]
Hello,
Do you have a SQL dump from affiliate-marketing Script?
mfg jens

**Comment by akramrana** [comment]
Yes...

> 
> 
> Hello,
> Do you have a SQL dump from affiliate-marketing Script?
> mfg jens

**Comment by jens40** [comment]
Can you download this here?

**Comment by akramrana** [comment]
> 
> 
> Can you download this here?

You probably asking for uploaded it right ? btw your account is looks suspicious. i cant see any  activity of your account.
Thank you.
